refactor: crew, attendance 테이블 분리
fromitive/java-wooteco-attendance pull request #10
Opened 2024-06-28 02:45 UTC by fromitive

이슈 #6에 따라 crew와 attendance의 테이블을 분리하여 아래와 같은 개선을 햇습니다.

1. attendance에 null값을 허용하지 않게 합니다
2. attendance에 많은 책임(출석 체크, setter를 통한 업데이트)를 줄였습니다.

2024-06-29 08:11 UTC, donghoony requested changes
@fromitive 포케 안녕하세요~~ 리뷰 확인했습니다. 아직 기능 추가된 것 없이 테이블 분리가 잘 이루어져서 크게 남길 코멘트는 없지만, 자잘한 코드 스타일이나 개선할 수 있는 부분을 남깁니다. 같이 토의해보아요 🔥

2024-06-29 08:11 UTC, donghoony commented on src/test/resources/test_data.sql
> +INSERT INTO crew (name, campus_name) VALUES ('혁수', '선릉');
```suggestion
INSERT INTO crew (name, campus_name) 
VALUES ('포케', '잠실'),
       ('아루', '잠실'),
       ('무송', '선릉'),
       ('동훈', '선릉'),
       ('혁수', '선릉');
```

2024-06-29 08:11 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Attendance.java
> +    private Attendance(final Long id, final Crew crew, final LocalDate date) {
출석 정보는 시각을 받지 않아도 괜찮나요 ? 지각 여부는 아직 기능에 없어서 그런걸까요 ?

2024-06-29 08:11 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Crew.java
`campus`를 enum으로 관리하면 어떨까요 ?

2024-06-29 08:11 UTC, donghoony commented on src/test/resources/test_data.sql
> +INSERT INTO attendance (crew_id, date) VALUES (2, CURRENT_DATE());
```suggestion
INSERT INTO attendance (crew_id, date) VALUES (2, CURRENT_DATE());

```

2024-06-29 08:11 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/repository/CrewRepository.java
> +    List<Crew> findByAbsentedCrew(LocalDate date);
- `a.id IS NULL`이 왜 필요한가요 ?
- 아래와 같은 메서드명은 어떨까요?
```suggestion
    List<Crew> findAbsentCrewsByDate(LocalDate date);
```

2024-06-29 08:11 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/AttendanceService.java
> +                LocalDate.now())
개행 없는 게 읽기 좋네요!
```suggestion
        return crewRepository.findByAbsentedCrew(LocalDate.now())
```

2024-06-29 08:11 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponse.java
> +                                   final String campusName) {
개행 없는 게 나을 것 같아요
````suggestion
    public AttendanceSheetResponse(final String rawDate, final String name, final String campusName) {
```

2024-06-29 08:11 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponse.java
>          this.date = LocalDate.parse(rawDate, DATE_PARSER);
고민할거리 : 파싱 책임이 Response에 있어도 좋을까요? Response는 값 객체니 외부에서 파싱해서 값을 전달해주는 건 어떤가요 ?

2024-06-29 08:11 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponses.java
> +            .filter(attendanceSheetResponse -> attendanceSheetResponse.getDate().isEqual(date))
객체에게 물어봅시다!
```suggestion
        .filter(response -> response.hasDateOf(date))
```

2024-06-29 08:17 UTC, donghoony commented
closes #6

2024-07-03 05:45 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Attendance.java
> +    private Attendance(final Long id, final Crew crew, final LocalDate date) {
출석폼을 제출하지 않는 크루들을 위한 것이라서 아직은 받고있지 않습니다 😄

2024-07-03 05:51 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/repository/CrewRepository.java
> +    List<Crew> findByAbsentedCrew(LocalDate date);
> a.id IS NULL이 왜 필요한가요 ?

출석폼을 제출하지 않은 크루를 확인해야 하는데, attendance에 저장되지 않은 크루들을 조회하기 위해서 필요합니다 

> 아래와 같은 메서드명은 어떨까요?

👍

2024-07-03 05:58 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Crew.java
좋아요~

2024-07-03 06:11 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponses.java
> +            .filter(attendanceSheetResponse -> attendanceSheetResponse.getDate().isEqual(date))
has 보다는 확인을 위해 보통 is가 직관적으로 잘 알 수 있을 것 같아요 😃 has로 한 이유가 있으실까요?

2024-07-03 07:13 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponses.java
> +            .filter(attendanceSheetResponse -> attendanceSheetResponse.getDate().isEqual(date))
Response는 응답이라는 의미이므로, 같다라는 의미인 `is`가 어색하다고 느꼈습니다. 응답에게 날짜를 가지고 있는지 물어보는 의도였어요!

2024-07-03 07:20 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponse.java
>          this.date = LocalDate.parse(rawDate, DATE_PARSER);
제가 잘 이해를 한 건지 모르겠어요! Response를 매개변수로 받아서 파싱하는 객체를 만들면 어떨까요?

2024-07-04 01:06 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Attendance.java
> +    private Attendance(final Long id, final Crew crew, final LocalDate date) {
출석폼을 제출하지 않는 크루는 (크루 중에서 - 오늘 날짜에 출석하지 않은 사람)을 뽑으면 어떤가요?

2024-07-04 01:06 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/repository/CrewRepository.java
> +    List<Crew> findByAbsentedCrew(LocalDate date);
위 답변과 이어지는데, `null`을 사용하는 것이 껄끄러워서 위 답변에서 설명한 대로 진행하면 어떨까요?

2024-07-04 01:07 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponse.java
>          this.date = LocalDate.parse(rawDate, DATE_PARSER);
`LocalDate.parse` 메서드가 Response 내부에 있어도 될지, 외부에서 파싱해서 `LocalDate`로 전달해야 할지를 고민해봐도 좋겠다 싶어서 포케의 의견을 듣고 싶었어요. 반영하지 않아도 됩니다 😅

2024-07-05 14:22 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Attendance.java
> +    private Attendance(final Long id, final Crew crew, final LocalDate date) {
현재 `AttendanceService`의 `createNewAttendances` 메서드에서 오늘 날짜에 출석하지 않는사람을 뽑고 있어요..! 

https://github.com/fromitive/milky-way/blob/29efd03bf93d38286afd49737db12541b5982d1a/src/main/java/woowacourse/crewniverse/milkyway/service/AttendanceService.java#L44-L46

2024-07-05 14:40 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/repository/CrewRepository.java
> +    List<Crew> findByAbsentedCrew(LocalDate date);
온갖 시도를 다 해봤는데, 현재 Attendance 테이블은 출석을 한 사람만 데이터가 저장되고 있기 때문에 출석을 하지 않는 크루의 정보는 가지고 있지 않아서 Crew 테이블을 주측으로 left join해야 해당 정보를 가지고 올 수 있네요 😢

2024-07-05 14:45 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Attendance.java
> +    private Attendance(final Long id, final Crew crew, final LocalDate date) {
추가 코멘트 달자면.. `AttendnaceService`의 `createNewAttendances`메서드를 아래와 같이 구성 해보는 시도를 해봤어요

1. AttendanceRepository에서 오늘 출석한 크루를 뽑는다. (이하 `crews`) 
2. AttendanceSheetResponses로 추가로 출석한 크루 정보를 뽑는다.  (이하 `newCrew`)
3. crews에 포함되지 않은 newCrew를 필터링하고 이를 업데이트 한다.

JPA 특성상 entity로 영속화 되지 않는 `Crew`객체는 저장할 수 없어서 위와 같이 구성했습니다. 😢 

 엔티티를

2024-07-05 15:00 UTC, fromitive commented
@donghoony 안녕하세요~ 😄 

변경할 수 없는 부분은 최대한 코멘트를 달았고, `IS NULL`, `출석폼을 제출하지 않는 크루 업데이트` 관련해서는 꼭 읽어주시길 부탁드려요

맞춤법, traliling comma 부분들도 검토해서 적용했으나, 놓친 부분이 있을 수 있으니 반영이 되어 있지 않으면 지적 부탁드리겠습니다

꼼꼼하게 봐주셔서 감사합니다 🙇

2024-07-06 10:55 UTC, donghoony requested changes
테스트가 통과하지 않네요 🥹 한 번만 확인해주세요~!

2024-07-06 10:55 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Campus.java
> +    @JsonCreator
JsonCreator 없어도 잘 동작하는 것 같은데, 필요한 어노테이션인가요? 아래 JsonValue도 마찬가지입니다

2024-07-06 10:55 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Campus.java
> +    }
```suggestion
                .filter(campus -> campus.hasNameOf(name))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("캠퍼스 명이 존재하지 않습니다 [%s]".formatted(name)));
```

2024-07-06 10:55 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/repository/CrewRepository.java
> +    List<Crew> findAbsentedCrewByDate(LocalDate date);
문법상 `AbsentCrew`가 적절합니다 😅

2024-07-06 10:55 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/repository/CrewRepository.java
> +    List<Crew> findByAbsentedCrew(LocalDate date);
오 그러네요, Crew를 기반으로 없는 것을 찾으려면 null을 사용해야겠습니다, 설명 고마워요 🤩

2024-07-06 10:55 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/AttendanceService.java
> +        final List<AttendanceSheetResponse> attendanceSheetResponses, final LocalDate today) {
```suggestion
    private List<Attendance> createNewAttendances(final List<AttendanceSheetResponse> attendanceSheetResponses,
                                                  final LocalDate today) {
```

2024-07-06 10:55 UTC, donghoony commented on src/test/resources/test_data.sql
> +                                              (2, CURRENT_DATE());
혹시 reformat 단축키로 아래와 같이 정렬되지 않나요?
```suggestion
INSERT INTO crew (name, campus)
VALUES ('포케', 'JAMSIL'),
       ('아루', 'JAMSIL'),
       ('무송', 'SEOLLEUNG'),
       ('동훈', 'SEOLLEUNG'),
       ('혁수', 'SEOLLEUNG');

INSERT INTO attendance (crew_id, date)
VALUES (1, CURRENT_DATE()),
       (2, CURRENT_DATE());
```

2024-07-06 10:55 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/AttendanceService.java
> +            .map(crew -> new Attendance(crew, today))
출석 기준 날짜가 어플리케이션 날짜가 아닌 Sheet에 적힌 날짜여야 하지 않을까요?

2024-07-06 10:55 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponse.java
> +        this.crew = new Crew(name, campus);
시트로부터 주어지는 Response에서 Crew를 생성할 책임이 존재하지 않는다고 생각해요, 서비스에서 값을 조작하는 게 낫지 않을까요? Campus와 name 정보만 가지고 있고, 서비스에서 크루 정보를 조회한 뒤 존재하지 않는 크루인 경우의 예외 처리도 필요하다고 생각해서요 (이건 다음 PR에서 진행하는 게 낫겠습니다)

2024-07-06 12:00 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/domain/Campus.java
> +    @JsonCreator
제거하는걸 잊고 있었네요 확인 감사합니다 😄

2024-07-06 12:09 UTC, fromitive commented on src/test/resources/test_data.sql
> +                                              (2, CURRENT_DATE());
h2 문법으로 설정되지 않아서 적용되지 않았나봅니다 😅

2024-07-06 12:19 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/service/AttendanceService.java
> +            .map(crew -> new Attendance(crew, today))
`updateAttendance` 에서 today를 기준으로 필터링 하고 있습니다.
후에 출석 시간을 활용하기 위해 Response에 있는 날짜 값을 저장하도록 변경할게요 😃

2024-07-06 12:21 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/service/response/AttendanceSheetResponse.java
> +        this.crew = new Crew(name, campus);
이부분은 response값을 dto의 책임만 두고 파싱하는 도메인을 별도로 분리하여 작업해봅시다!

2024-07-06 12:27 UTC, fromitive commented
> 테스트가 통과하지 않네요 🥹 한 번만 확인해주세요~!

안녕하세요 @donghoony 해당 테스트 확인 결과, 의도가 잘못 되어서(출석하지 않은 크루 수를 확인해야 하는데 출석한 크루를 확인하였음) 해당 테스트 수정했습니다. 꼼꼼히 확인해주셔서 감사합니다.

그 외 코멘트는 반영했으니 merge하겠습니다!

2024-07-06 12:27 UTC, merged