refactor: 프로젝트명 설정에 따른 패키지 구조 수정
fromitive/java-wooteco-attendance pull request #5
Opened 2024-06-24 08:43 UTC by donghoony

패키지 구조를 `woowacourse.crewniverse` 아래로 두고, 현재 프로젝트명인 `milkyway` 패키지 아래에 위치하도록 프로젝트 패키지를 변경합니다.

2024-06-24 08:59 UTC, fromitive commented
테스트 실행 결과 아래와 같이 Production코드의 Config가 생성되어 오류가 발생하는 것 같아요!
git으로 관리되지 않은 파일인 credentials.json도 없으면 오류가 나는데 개선이 필요합니다..! 

<img width="1029" alt="image" src="https://github.com/crewniverse/milky-way/assets/46563149/76d4a912-8ff5-47e7-a996-5371afa6bcf3">

2024-06-25 08:28 UTC, donghoony commented on src/test/resources/application.yml
> +
기존 `@Configuration`이 프록시로 설정돼있기 때문에, 직접 접근하기 이전에는 빈이 생성되지 않아 에러가 발생하지 않습니다. 어플리케이션이 실행될 때, 이름이 같은 빈이 등록되는 경우 빈을 덮어쓸 수 있는데요, 이를 활용해 보았습니다. 여전히 좋은 해결 방안이라고 생각되지는 않네요 😅

2024-06-25 10:15 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/config/GoogleCrawlerConfiguration.java
> +        return new GoogleSheetCrawler(sheetsService, sheetOption);
timeout, GoogleOAuth 인증부분을 Creator로 캡슐화 시킨 것인데 로직을 들어낸 이유가 있나요?

2024-06-25 10:19 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/httpclient/googlesheet/GoogleCredentials.java
> +                GsonFactory.getDefaultInstance(), new InputStreamReader(in)
`GoogleCrawlerConfiguration`에 있는 GsonFactory를 활용하지 않은 이유는 .getDefaultInstance 에서 얻은 객체가 싱글턴이라서 그런것일까요?

2024-06-25 10:26 UTC, fromitive requested changes
안녕하세요 @donghoony!

`sheetsService`로 `GoogleSheetCrawler`의 역할이 명확해짐을 느꼈습니다. 

`GoogleCrawlerConfiguration` 코드 중 궁금한 사항이 있어서 코멘트 남깁니다.

2024-06-25 10:28 UTC, fromitive commented on src/test/resources/application.yml
> +
어제 같이 고군분투를 했었는데 깔끔하게 분리하는 방법이 잘 떠오르지 않네요 😅
해당 부분은, issue로 남겨 놓고, 경험치가 차면 천천히 해결하시죠!
고생하셨습니다. 🙇

2024-06-25 10:45 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/config/GoogleCrawlerConfiguration.java
> +        return new GoogleSheetCrawler(sheetsService, sheetOption);
기존 Creator가 단순 메서드를 클래스로 뽑았다는 느낌이었어요. 매번 크롤링 시마다 빌더가 인스턴스를 매번 생성하기도 하고요.
현재 부분에서 로직이 드러났다고 보이는 부분이 있나요? Google API에서 제공하는 `Sheets.Builder`를 활용해 인스턴스를 만드는 것이라 조금 더 직관적이지 않나요?

2024-06-25 10:46 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/httpclient/googlesheet/GoogleCredentials.java
> +                GsonFactory.getDefaultInstance(), new InputStreamReader(in)
넵 `global thread-safe instance`라고 명시돼 있어서 따로 빈으로 등록하지 않고 그냥 가져다 썼어요

2024-06-25 11:18 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/config/GoogleCrawlerConfiguration.java
> +        return new GoogleSheetCrawler(sheetsService, sheetOption);
sheets 빌더가 기존에는 crawl메서드에 들어가있어서 크롤링 할 때마다 매 번 생성되었군요! 이부분은 말씀 주신 것 처럼configuration에 들어내는 것이 자연스러워 보입니다.

다만, Sheets.builder는 HttpRequestInitializer를 받는 거라 credential 객체만 넣어도 잘 생성이 되는데(credential이 HttpRequestInitializer 구현체),

credential와 timeout과 합칠 수 있으면 묶어놓는 편이 자연스러워 보였습니다!

2024-06-25 11:27 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/config/GoogleCrawlerConfiguration.java
> +        return new GoogleSheetCrawler(sheetsService, sheetOption);
같은 `HttpRequestInitializer`를 구현했지만, Sheet쪽으로 보내는 것에 대한 Timeout과 OAuth를 진행하기 위한 부분은 서로 다른 관심사라고 생각해서 합쳐두지 않았습니다. `Credentials`에서는 Google OAuth 인증만을 담당하도록 의도했어요 !

2024-06-25 11:48 UTC, merged