refactor: 패키지 구조 수정
fromitive/java-wooteco-attendance pull request #7
Opened 2024-06-25 15:00 UTC by donghoony

기존 패키지 구조를 조금 다듬습니다. 대표적으로는 아래와 같아요.
- `config`의 위치가 base package 바로 아래라, 전역으로 적용될 수 있어보입니다. 이를 `googleclient` 아래로 옮겨 클라이언트 관련 설정임을 의도했습니다.
- `response`에서도 마찬가지로, 이를 사용하는 `service` 아래에 두었습니다.
- `Crawler`의 구현체와 인터페이스 패키지를 구분했습니다. 구현체는 주로 `google`에 있으며, 이제 `service`에서 크롤러 구현체 패키지를 모릅니다 😄
- `Option`보다 스프링에서 사용하는 `ConfigurationProperties`에서 `Properties`를 따와 클래스명을 수정했습니다.

다른 PR에 올려야하지 싶지만 얹은 내용으로:
- NotAttended보다 가독성이 좋은 Absent (결석)을 사용하는 방향으로 변수/메서드명을 수정했습니다.

더 생각해볼 사항 및 할 이야기
- 코드 스타일에 개입하는 느낌이 들어서, 확인해 주세요. 단호한 피드백도 좋습니다 😄
- 크롤러/서비스 쪽 로직을 다듬을 필요가 있어 보입니다. 특히 SheetResponse/SheetResponses 쪽 로직이 아직은 머리에 잘 들어오지 않아서 테스트를 작성해봐야겠어요 😅
- 아자아자 🔥

2024-06-27 18:33 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/controller/AttendanceController.java
> +        List<AttendanceResponse> attendanceResponses = attendanceService.getAbsentCrew();
부정문 보다는 한 단어로 표현하는게 좀 더 가독성 있네요 👍

2024-06-27 18:45 UTC, fromitive commented on src/main/java/woowacourse/crewniverse/milkyway/googleclient/GoogleSheetCrawler.java
> +    private final Sheets sheetsService;
Sheets의 필드명을 sheetsService로 한 이유가 있을까요?

2024-06-27 19:31 UTC, fromitive requested changes
안녕하세요 @donghoony 

PR 재밌게 봤습니다 😄 기존 SheetOption과 같은 설정 값을 확인하는 객체를 Property라는 네이밍을 붙인점 그리고 , 부정문(NotAttended)을 한 단어(Absent)로 변경하여 좀 더 가독성이 생겼음을 느꼈습니다.

아래는 주신 코멘트에 대해 궁금한 부분들을 정리한 내용입니다.

> config의 위치가 base package 바로 아래라, 전역으로 적용될 수 있어보입니다. 이를 googleclient 아래로 옮겨 클라이언트 관련 설정임을 의도했습니다.

config 패키지 안에 googleclient 패키지를 넣어서 설정들만 관리해주는건 어떻게 생각하시나요?

기능이 확장되면 하위 패키지에 config가 중복으로 생성될 것 같습니다.
또한, config가 있거나 없는 패키지가 생기는 등 일관성이 없어질 것 같아요.

> response에서도 마찬가지로, 이를 사용하는 service 아래에 두었습니다.

response를 service로 두는 이유는 service에서 response 객체를 생성하기 때문일까요? response, request와 같은 dto위치의 기준이 궁금합니다.

> Crawler의 구현체와 인터페이스 패키지를 구분했습니다. 구현체는 주로 google에 있으며, 이제 service에서 크롤러 구현체 패키지를 모릅니다 😄

이부분은 저한테는 익숙하지 않아 어색하게 다가왔어요. service 패키지는 온전히 service 객체만 들어있어야 한다고 생각합니다. 코드를 읽다가 crawler 인터페이스만 service 패키지에 속해 있으면, repository도 sevice 패키지에 있어야 하지않나요? 그렇게 하지 않은 이유가 있을까요?
service와 crawler는 다른 성격을 가지고 있는데, 의존하고 있음을 드러내도록 패키지를 분리하는 것이 가독성이 좋다고 생각하는데, 이전에 저와 같은 생각을 하셨다면 어떻게 생각의 전환을 하게 된 것일까요? 

혹시 제가 오해했거나, 잘못된 표현을 사용했다면 피드백 부탁드립니다!! 🙇 

화이팅 화이팅! 🔥

2024-06-28 07:33 UTC, donghoony commented on src/main/java/woowacourse/crewniverse/milkyway/googleclient/GoogleSheetCrawler.java
> +    private final Sheets sheetsService;
처음 물어봐줬을 때 저도 긴가민가했는데, 공식 문서에서 따랐었네요. 
`Service definition for Sheets (v4).` ([reference](https://developers.google.com/resources/api-libraries/documentation/sheets/v4/java/latest/com/google/api/services/sheets/v4/Sheets.html))

2024-06-28 07:42 UTC, donghoony commented
> config 패키지 안에 googleclient 패키지를 넣어서 설정들만 관리해주는건 어떻게 생각하시나요?

Spring을 기반으로 하는 Web Config의 경우에는 전역으로 놓아도 된다고 생각합니다. `Interceptor`나 `ArgumentResolver`와 같이요. 다만 외부 API인 구글 클라이언트에 종속되는 환경설정이 전역 패키지에 놓이는 게 다소 적절하지 않다고 판단했습니다.

> response를 service로 두는 이유는 service에서 response 객체를 생성하기 때문일까요? response, request와 같은 dto위치의 기준이 궁금합니다.

마찬가지로 전역 패키지보다는 사용하는 Service 레이어에서 정의하는 것이 더 좋다고 판단했습니다. Controller에 두는 방법도 있었겠지만, dto의 내부 변수는 서비스에서 사용하는 것을 정의하는 것이 보통이므로 이를 서비스단에 두었어요.

> 이부분은 저한테는 익숙하지 않아 어색하게 다가왔어요. service 패키지는 온전히 service 객체만 들어있어야 한다고 생각합니다. 코드를 읽다가 crawler 인터페이스만 service 패키지에 속해 있으면, repository도 sevice 패키지에 있어야 하지않나요? 그렇게 하지 않은 이유가 있을까요?
service와 crawler는 다른 성격을 가지고 있는데, 의존하고 있음을 드러내도록 패키지를 분리하는 것이 가독성이 좋다고 생각하는데, 이전에 저와 같은 생각을 하셨다면 어떻게 생각의 전환을 하게 된 것일까요?

외부 API의 측면에서 인터페이스를 분리했지만, 인터페이스를 분리함으로써 얻을 수 있는 이점이 한 가지 더 있다고 봅니다. 구현체와 인터페이스의 분리가 이에 해당하는데요, JDBC도 인터페이스만 정의해놓고, H2와 MySQL 등이 이를 구현해 라이브러리로 제공합니다. 그렇다고 해서 H2나 MySQL과 같은 벤더사의 라이브러리 안에 JDBC가 들어있지는 않아요. 
만드는 입장이 아닌, 사용하는 입장에서도 구현체에 의존하는 것보다는 인터페이스에 의존하는 것이 변경에 보다 유연합니다. 나아가 이 의존은 단순 코드에서 드러나는 것뿐만이 아니라, 패키지로 바라보아야 한다고 생각해요.

서비스에서는 크롤러를 사용합니다. 어떤 연산이 있는지만 인터페이스를 통해 알고 있고, 이를 구글API를 활용해 제공합니다. 저는 외부 API를 사용하는 코드와 기존 코드 분리를 철저하게 할수록 변경에 유연해진다고 생각해요. 레벨 1에 이와 관련된 [리뷰어 코멘트](https://github.com/woowacourse/java-ladder/pull/342#pullrequestreview-1902865991)가 있었는데, 확인해보셔도 좋겠습니다.

추가로 궁금하신 사항 있으면 물어봐주세요요~

2024-06-28 07:55 UTC, donghoony commented
위 코멘트에 이어서: 여전히 Service와 Crawler가 다른 역할을 한다고 생각한다면 패키지를 나누겠지만, 단지 크롤러 인터페이스 하나만 들어있을 패키지를 나누는 건 의미가 없어 보였습니다 !

2024-06-28 08:00 UTC, fromitive approved these changes
안녕하세요 @donghoony 코멘트 잘 읽었습니다.

인터페이스 정의는 인터페이스를 정의하는 구현체가 아닌 이를 사용하는 객체를 중심으로 구성해야 한다는 점을 배웠네요 이를 통해 사용하는 주체는 구현체를 알고있지 않아도 되는 것이 어떤건지 알게되었습니다. 😄 감사합니다

> 여전히 Service와 Crawler가 다른 역할을 한다고 생각한다면 패키지를 나누겠지만, 단지 크롤러 인터페이스 하나만 들어있을 패키지를 나누는 건 의미가 없어 보였습니다 !

이부분에 대해서도 저도 공감이 가는데요, 이는 지금 판단할 수 있는 사항이 아니기 때문에 기능을 추가로 확장하면서 별도로 분리하시죠. 
머지하겠습니다. 감사합니다. 🙇

2024-06-28 08:00 UTC, merged